<?php
/**
 * When menu option create is selected,it will open create.php file which will ask the employee to enter credentials
 * of the new bank customer like name, phone number, initial balance, address. Customer id is generated by the sytem.
 * All these entries will go to the database via javascript.
 */
session_start();
$access = isset($_SESSION["userid"]);
?>

<!DOCTYPE html>
<html>

<head>
    <title>Login Example</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
    body {
    width: 8in;
    height: 12in;
    border-style: solid;
    border-width: 5px;
    background-image: url("tile.jpg");
    background-repeat: repeat;
    background-size: cover;
    font-family: "Times New Roman", sans-serif;
    font-weight: bold;
    font-size: 18pt;
    }
    input[type=text] { 
        background-color: rgb(230, 186, 173); 
        height:25px; 
        font-size:20px; 
        border-radius:10px; 
        margin-top: 20px;
                    }
    input[type=password] { 
        background-color: rgb(173, 200, 230); 
        height:25px; 
        font-size:20px; 
        border-radius:10px; 
        margin-top: 20px;
                    }
    input[type=color] { 
        background-color: rgb(230, 212, 173); 
        height:25px; 
        font-size:20px; 
        border-radius:10px; 
        margin-top: 20px;
            }
    input[type=number] { 
        background-color: rgb(230, 212, 173); 
        height:25px; 
        font-size:20px;
        border-radius:10px; 
        margin-top: 20px;
            }



    input[type=submit]{
        background-color: rgb(236, 142, 78);
        height:50px; 
        width: 2in;
        font-size:44px; 
        border-radius:10px; 
        margin-top: 0.2in;;
        margin-left: 0.5in;
        float: left;
        margin-bottom:0.2in;
    }

    input[type= button]{
        background-color: rgb(238, 255, 0);
        height:50px; 
        width: 2in;
        font-size:20px; 
        border-radius:10px; 
        margin-top: 0.02in;;
        margin-left: 0.5in;

    }
    p{
        display: inline-block;
    }

    #game{
        position: absolute;
        float: top;
    }
    #game.h1{
        position:relative;
    }
    #main{
		display: inline-block;
		width: 7in;
		height: 5in;
		margin-left:0.1in;
		border-width: 4px;
		border-style: solid;
		border-color:red blue green blue;
        padding-left: 0.1in;
    }
    #target{
        display: inline-block;
		width: 7in;
		height: 4.5in;
		margin-left:0.1in;
		border-width: 4px;
		border-style: solid;
		border-color:red blue green blue;
        padding-left: 0.1in;
    }
    </style>
    <script src="banksystem.js"></script>
</head>

<body>
    <?php
    if ($access) {
        echo "<a href='menu.php'>back</a>";
        echo "<h1>Create New Account</h1>";
        
        echo "<div id='main'>
        <h1 id='message' class='heading'>Customer Service Login!!</h1>
        <form id='mainform'>
          
           First Name:<input type='text' id='firstname' name='firstname' size=20px placeholder='First Name' required autofocus><br>
           Last Name:<input type='text' id='lastname' name='lastname' size=20px placeholder='Last Name' required autofocus><br> 
           Address:<input type='text' id='addres' name='addres' size=20px placeholder='Address' required autofocus><br> 
           Phone No:<input type='Number'id='phone' name='phone' size=20px placeholder='Phone Number' required autofocus><br> 
           Starting Balance:<input type='Number' id='balance' name='balance' size=20px placeholder='Starting Balance' required autofocus><br> 
           <input type='button' id='addcustomerbutton' value='Update'>
        </form>
              </div>";
           echo"<span id='target'>
                    <table id='table'border = 10px><tr>
                      <th>First Name</th>
                      <th>Last Name</th>
                      <th>Customer Id</th>
                      <th>Address</th>
                      <th>Phone Number</th>
                      <th>Balance</th>
              </tr>
                      </table>
      </span>";
    }
    else {
        echo "<h1>Not Logged in. Access denied.</h1>";
    }
    ?>
</body>

</html>